YouTubeDownloader/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^downloader/', include('downloader.urls')),
]

downloader/urls.py
from django.conf.urls import url
from . import views

app_name='downloader'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^wizzyDownload/$',views.details,name='details'),
    url(r'^wizzyDownload/download/$',views.download,name='download'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'^profile/$',views.profile, name='profile')
]

downloader/models.py
from django.db import models
from django.contrib.auth.models import Permission,User

class Video(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
	video = models.CharField(max_length=255)
	date = models.DateField()

	def __str__(self):
		return self.user.username+" "+self.video

downloader/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','email','password']

downloader/views.py
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from pytube import YouTube
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.views import generic
from django.views.generic import View
from .forms import UserForm
from .models import Video
from django.contrib.auth.models import User,Permission
import datetime

def index(request):
	template = loader.get_template('downloader/index.html') 
	context = {}
	return HttpResponse(template.render(context,request))

def details(request):
	if not request.user.is_authenticated():
		return render(request,'downloader/login.html',{'error_message':'You must login to access this feature'})
	else:
		template = loader.get_template('downloader/wizzyDownload.html') 
		context = {}
		return HttpResponse(template.render(context,request))

def profile(request):
	if not request.user.is_authenticated():
		return render(request,'downloader/login.html',{'error_message':'You must login to access this feature'})
	template = loader.get_template('downloader/profile.html')
	name = request.session["curr_user"]
	u = User.objects.get(username = name)
	vidlist = u.video_set.all()
	if len(vidlist) > 6:
			vidlist = vidlist[len(vidlist)-6:]
	context = {"user":u,"all_video" : vidlist}
	return HttpResponse(template.render(context,request))

def download(request):
	id = request.GET['url']
	#print("The String to be Downloaded is :: "+id)
	try:
		yt = YouTube(str(id)).streams.first().download()
		#yt = YouTube(id)
		#print(" Video : "+str(yt.filter('mp4')[-1]))
		#video = yt.filter('mp4')[-1]
		#video.download('/tmp/')
		message="Download Complete"
		#putting the song into the database
		name = request.session["curr_user"]
		u = User.objects.get(username=name)
		v = Video()
		v.user = u
		v.date = datetime.datetime.now().date()
		v.video = id
		v.save()
	except Exception as e:
		print(""+str(e))
		message = "Please enter a valid url Or check your Internet Connection"
		return render(request,'downloader/wizzyDownload.html',{'message':message})
	return render(request,'downloader/wizzyDownload.html',{'message':message})

class UserFormView(View):
	form_class = UserForm
	template_name = 'downloader/registration_form.html'
	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)
		if form.is_valid():
			user = form.save(commit = False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			user = authenticate(username=username,password=password)
			if user is not None:
				if user.is_active:
					login(request,user)
					request.session['curr_user']=username
					return redirect('downloader:index')

		return render(request,self.template_name,{'form':form})

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username='sanjeev45@',password='sanjeev@')
		if user is not None:
			if user.is_active:
				login(request,user)
				request.session['curr_user']='sanjeev45@'
				return render(request,'downloader/index.html')
			else:
				return render(request,'downloader/login.html',{'error_message':'Your account has been disabled'})
		else:
			return render(request,'downloader/login.html',{'error_message':'Invalid login'})
	return render(request,'downloader/login.html')

def logout_user(request):
	if "curr_user" in request.session:
		del request.session['curr_user']
	logout(request)
	form = UserForm(request.POST or None)
	context = {
		"form":form,
	}
	return render(request,'downloader/login.html',context)

downloader/templates/downloader/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Song Page{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script rel="text/javascript" src="{% static 'downloader/js/typed.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'downloader/css/styling.css'%}">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Barrio|Roboto|Play|Tangerine|Lobster|Abril+Fatface|Indie+Flower|Oxygen|Roboto+Mono|Aldrich|Merienda|Playfair+Display+SC|Rock+Salt"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<!--To fix nav bar add class  navbar-fixed-top-->
<div class="navbar navbar-light">
	<div class="container fluid">
		<div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
			<a class="navbar-brand brandText" href="{% url 'downloader:index' %}">Wizzy</a>&nbsp;&nbsp;
		</div>

        <!-- HEader-->

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active navlist">
                    <a href="{% url 'downloader:index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                            <span class="topText">Home</span>
                    </a>
                </li>
                <li class="navlist">
                    <a href="{% url 'downloader:details' %}">
                        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>&nbsp;
                            <span class="topText">Downloader</span>
                    </a>
                </li>
                <li class="navlist">
                    <a href="{% url 'downloader:profile' %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;
                            <span class="topText">Profile</span>
                    </a>
                </li>
            </ul>

            <!--Right side buttons-->
            <ul class="nav navbar-nav navbar-right">
                <li class="navlist">
                    <a href="#">
                        <span class="topText">
                            {% if "curr_user" in request.session %}
                                {{ request.session.curr_user}}
                            {% else %}
                                DEFAULT
                            {% endif %}
                        </span>
                    </a>
                </li>
                <li class="navlist">
                    <a href="{% url 'downloader:login_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            <span class="topText">Login</span>
                    </a>
                </li>
                <li class="navlist">
                    <a href="{% url 'downloader:register' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            <span class="topText">Signup</span>
                    </a>
                </li>
                <li class="navlist">
                    <a href="{% url 'downloader:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            <span class="topText">LogOut</span>
                    </a>
                </li>
            </ul>

        </div>
	</div>
</div>

{% block content %}
{% endblock %}
</body>
</html>

downloader/templates/downloader/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">
        <!-- Form Fields Are being Accessed Using the name attribute-->
        <input type="text" class="form-control" name="{{ field.name }}" id="id_{{ field.name }}" placeholder="{{ field.label }}" />
       </div>
    </div>
{% endfor %}

downloader/templates/downloader/index.html
{% extends 'downloader/base.html'%}

{% block title %}Wizzy Downloader{% endblock %}

{% block content%}
<div class="mainEntry">
<h1 class="allheads"><strong>Wizzy Downloader</strong></h1>
	<div id="typed-strings">
		<p>Download Videos</p><p><em>Free</em> Downloads</p><p>YouTube <strong>Dechiphered</strong></p>
	</div>
	<div id="typecon"><span id="typed"></span></div>
</div>
<hr><hr><hr>
<br><br>
<div class="row fact-1 divcons">
	<div class="container">
		<div class="col-md-6">
			<br><br><br><br><br><br>
			<p>Free Download of any youtube video.</p>
			<p style="text-align:right">Grab the link Paste It and <em>Viola!</em></p>
			<p>High quality video downloaded.</p>
			<p style="text-align:right">Very Simple and UserFriendly UI </p>
		</div>
		<div class="col-md-5 col-md-offset-1">
			<img src="http://i.imgur.com/9bGaJxr.png" alt="image not loaded" class="img img-responsive" height=400 width=400>
			<br><br>
		</div>
	</div>
</div>
<div class="row fact-2 divcons">
<br><br><br><br>
	<div class="container">
		<div class="col-md-5">
			<img src="http://i.imgur.com/TNWfKIm.png" alt="image not loaded" class="img img-responsive" height=400 width=400>
			<br><br><br><br>
		</div>
		<div class="col-md-6  col-md-offset-1">
			<br><br>
			<p>Create your own <em>Account</em></p>
			<p style="text-align:right">Maintain a list of all your Downloads</p>
			<p>Easily revisit downloaded links on <em>YouTube</em></p>
			<p style="text-align:right">Sign Up now to enjoy other benefits</p>
			<br><br>
		</div>
	</div>
</div>
<div class="row fact-3">
<br><br><br><br>
	<div class="container">
		<div class="col-md-4">
			<div class="footerCons">
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://www.shareicon.net/download/2016/11/14/852208_download_512x512.png" width=300 height=300>
				<p class="footText"><a href="{% url 'downloader:details' %}">Go to the Downloader Page</a></p>
				<br>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footerCons">
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://image.freepik.com/free-icon/user-check-interface-symbol_318-60830.jpg" width=300 height=300>
				<p class="footText"><a href="{% url 'downloader:profile' %}">Visit Profile Page</a></p>
				<br>
			</div>
		</div>
		<div class="col-md-4">
			<div class="footerCons">
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://www.youtube.com/yt/brand/media/image/YouTube-logo-dark.png" width=300 height=300>
				<p class="footText"><a href="https://www.youtube.com/" target="_blank">Visit YouTube</a></p>
				<br>
			</div>
		</div>
	</div>
	<br><br>
</div>
<div class="footerElement">
	<p class="footText" style="color:white">This site has been completely developed in <strong>Django Framework</strong></p>
</div>
<script>
var images = ["http://i.imgur.com/vfwvVg6.jpg","http://i.imgur.com/aa9dQbT.jpg","http://i.imgur.com/hB9BkIl.png","http://i.imgur.com/MrCK2sg.jpg","http://i.imgur.com/AF5I0JZ.png","http://i.imgur.com/A8HX0SH.png","http://i.imgur.com/1bCpo8q.jpg","http://i.imgur.com/gKIUh1g.png"];
var index = 1;
document.addEventListener('DOMContentLoaded', function(){
		Typed.new('#typed', {
			stringsElement: document.getElementById('typed-strings')
		});
});

$(document).ready(function(){
	$(".allheads").addClass("animated tada");
	function slider(){
		$(".mainEntry").css("background-image","url('"+images[index]+"')");
		index++;
		if(index === images.length)
			index=0;
	}
	setInterval(slider,5000);
});

</script>
{% endblock %}

downloader/templates/downloader/login.html
{% extends 'downloader/base.html' %}
{% block title %}Log In{% endblock %}

{% block content %}
<h1 class="regHead">Existing User : LOGIN</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3 style="text-align: center;letter-spacing: 2px;"><b>LOGIN INFORMATION</b></h3>
                    <br>
                    {% if error_message %}
                        <p style="color:red;text-align: center;"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'downloader:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-sm-offset-3" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-5">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-sm-offset-3" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-5">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-5">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'downloader:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

downloader/templates/downloader/profile.html
{% extends 'downloader/base.html' %}
{% block title %}Profile:{{user.username}}{% endblock %}
{% block content %}
<div class="row">
	<div class="container-fluid">
		<div class="col-xs-12 col-md-12 photo">
			<br>
			<center>
				<div class="photo-div">
					<img src="http://i.imgur.com/8ka8RPi.png" class="img img-responsive" style="width:100%;height:100%;"/>
				</div>
			</center>
			<br>
			<center>
				<div class="information">
					<span class="profileText">Username : <i>{{user.username}}</i></span>
					<br>
					<span class="profileText">Email : <i>{{user.email}}</i></span>	
				</div>
			</center>
		</div>
	</div>
</div>
<h2 class="allheads">Previous Downloads</h2>
<table class="table table-striped">
	<thead>
		<th>Previous Downloads</th>
		<th>Linked Video</th>
		<th>Date of Download</th>
	</thead>
	{% for video in all_video|slice:':6' %}
	<tr>
		<td class="link-vid"><a href="{{ video.video }}" target="_blank">{{ video.video }}</a></td>
		<td class="vid">
			<div class="row">
			  <div class="col-sm-12">
			    <div class="bs-example" data-example-id="responsive-embed-16by9-iframe-youtube">
			      <div class="embed-responsive embed-responsive-4by3">
			        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.video|slice:'32:' }}"></iframe>
			      </div>
			    </div>
			  </div>
			</div>
		</td>
		<td class="date-vid">{{ video.date }}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

downloader/templates/downloader/registration_form.html
{% extends 'downloader/base.html'%}
{% block title%}Register{% endblock %}
{% block content %}
<h1 class="regHead">Welcome New User</h1>
<br>
<h2 class="regHead">Create an Account</h2>
<div class="row">
 	<div class="container-fluid">
        <div class="col-md-offset-2 col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'downloader/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

downloader/templates/downloader/wizzyDownload.html
{% extends 'downloader/base.html'%}

{% block title %}Wizzy YouTube Downloader{% endblock %}

{% block content%}

{% if message %}
	<script>window.alert("{{message}}")</script>
{% endif %}

<h1 class="allheads">Make a Wizzy Download ...... </h1>
<form action="{% url 'downloader:download' %}" method="get">
	{% csrf_token %}
	<input type="text" name="url" id="downloadField" placeholder="Enter the URL to be Downloaded" />
	<input type="button" class="btn btn-success downloadBtn" id="CheckBtn" value="Check URL"/> 
	<input type="submit" class="btn btn-success downloadBtn" value="Download"/> 
</form>
<br><br><br>
<p class="error" style="text-align:center;color:red;font-size:130%"></p>
<br><br>
<div class="row">
	<div class="container">
		<div class="col-md-5 col-md-offset-1 videoDiv" style="background-color: red;">
		</div>
		<div class="col-md-4 infoDiv" style="background-color: white;">
		</div>
	</div>
</div>
<script>
$(document).ready(function(){
	$("#CheckBtn").on("click",function(){
		var dn_str = $("#downloadField").val();
		console.log(dn_str);
		var re = /https:\/\/www\.youtube\.com\/watch\?v=/;
		var bool = re.test(dn_str);
		if(bool){
			$(".videoDiv").css("opacity","1.0");
			$(".infoDiv").css("opacity","1.0");
			var ifr_str = "https://www.youtube.com/embed/";
			ifr_str += dn_str.substring(dn_str.indexOf("?")+3);
			console.log(ifr_str); 
			var str_html="<div class='embed-responsive embed-responsive-4by3'><iframe class='embed-responsive-item' src='"+ifr_str+"'></iframe></div>";
			$.ajax({
				url: "https://crossorigin.me/"+dn_str,
     			dataType: 'html',
     			//type : "post",
     			success: function(data) {
			     		var title = $(data).find("#eow-title").text();
			     		$(".infoDiv").html("<p class='info'><strong>"+title+"<br><p>Click on download to download the best quality mp4</strong></p></p>");
			    }
			});
			$(".videoDiv").html("");
			$(".error").html("");
			$(".videoDiv").html(str_html);
		}else{
			$(".error").html("<strong>Please enter a valid url</strong>");
		}	
		//console.log(bool);
	});
});
</script>
{% endblock %}